import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router';
import { useAuth } from '@/lib/auth';
import { ai as aiApi } from '@/lib/api';
import GuestGate from '@/app/components/GuestGate';
import { Loader2, ArrowLeft, Sparkles, Brain, Check, Calendar, TrendingUp } from 'lucide-react';

export default function Discoveries() {
  const { user } = useAuth();
  const navigate = useNavigate();

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [history, setHistory] = useState<any[]>([]);

  useEffect(() => {
    if (!user) {
      setLoading(false);
      return;
    }

    aiApi.getDailyDiscoveryHistory()
      .then((res) => {
        setHistory(res || []);
      })
      .catch((err) => {
        setError(err.message || 'Failed to load discovery archive.');
      })
      .finally(() => {
        setLoading(false);
      });
  }, [user]);

  if (!user) {
    return (
      <GuestGate
        title="ARIA Discovery Archive"
        description="Sign in to unlock and browse through your daily behavioral insights."
        icon={<Sparkles className="w-8 h-8 text-accent animate-pulse" />}
      />
    );
  }

  if (loading) {
    return (
      <div className="min-h-[50vh] flex flex-col items-center justify-center space-y-4">
        <Loader2 className="w-8 h-8 text-accent animate-spin" />
        <p className="text-sm text-text3">Fetching your daily discovery archive...</p>
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto space-y-8 animate-fadeIn text-left">
      {/* Header */}
      <div className="flex items-center gap-4 border-b border-border pb-4">
        <button
          onClick={() => navigate('/dashboard')}
          className="p-2 hover:bg-bg3 rounded-full text-text3 hover:text-text transition-all smooth-hover-btn"
        >
          <ArrowLeft size={18} />
        </button>
        <div>
          <div className="text-xs text-accent tracking-[0.1em] uppercase mb-1">ARCHIVE</div>
          <h1 className="text-2xl sm:text-3xl font-light text-text font-[family-name:var(--font-serif)]">Discovery History</h1>
          <p className="text-xs text-text3 mt-0.5">Browse past behavioral insights and correlations generated by ARIA.</p>
        </div>
      </div>

      {error ? (
        <div className="bg-rose/10 border border-rose/25 rounded-2xl p-5 text-center text-rose text-sm">
          ⚠️ {error}
        </div>
      ) : history.length === 0 ? (
        <div className="bg-bg3 border border-border rounded-3xl p-12 text-center space-y-4">
          <Brain className="w-12 h-12 text-text3 mx-auto opacity-40" />
          <h3 className="text-base font-semibold text-text">No Discoveries Recorded Yet</h3>
          <p className="text-xs text-text3 max-w-sm mx-auto leading-relaxed">
            ARIA generates a new discovery every 24 hours based on your mood logs and journals. Complete daily check-ins to build confidence scores!
          </p>
          <button
            onClick={() => navigate('/dashboard')}
            className="px-6 py-2 bg-accent hover:bg-accent2 text-white font-semibold rounded-full text-xs transition-all shadow-md smooth-hover-btn"
          >
            Back to Dashboard
          </button>
        </div>
      ) : (
        <div className="relative border-l border-border pl-6 ml-4 space-y-8">
          {history.map((item) => {
            const dateStr = new Date(item.created_at).toLocaleDateString(undefined, {
              month: 'short',
              day: 'numeric',
              year: 'numeric'
            });

            return (
              <div key={item.id} className="relative space-y-3">
                {/* Timeline Dot */}
                <div className="absolute -left-[31px] top-1.5 w-4 h-4 rounded-full bg-bg border-2 border-accent flex items-center justify-center">
                  <div className="w-1.5 h-1.5 rounded-full bg-accent" />
                </div>

                <div className="bg-bg2 border border-border rounded-[20px] p-5 space-y-3 hover:border-accent/30 transition-all shadow-md">
                  <div className="flex items-center justify-between text-xs text-text3">
                    <span className="flex items-center gap-1.5 font-light">
                      <Calendar size={12} />
                      {dateStr}
                    </span>
                    <span className="font-semibold text-teal bg-teal-dim border border-teal/20 px-2 py-0.5 rounded-full">
                      Confidence: {item.confidence_score}%
                    </span>
                  </div>

                  <p className="text-sm font-medium text-text leading-relaxed">
                    "{item.discovery_text}"
                  </p>

                  {/* Supporting Evidence Stats */}
                  {item.supporting_evidence && Object.keys(item.supporting_evidence).length > 0 && (
                    <div className="bg-bg3/60 rounded-xl p-3 border border-border/40 space-y-1.5">
                      <div className="text-[10px] text-text3 font-bold uppercase tracking-wider flex items-center gap-1">
                        <TrendingUp size={10} className="text-accent" /> Supporting Evidence
                      </div>
                      <div className="grid grid-cols-2 gap-3 text-[11px] font-light">
                        {Object.entries(item.supporting_evidence).map(([key, val]) => {
                          const formattedKey = key
                            .replace(/_/g, ' ')
                            .replace(/\b\w/g, (c) => c.toUpperCase());
                          return (
                            <div key={key} className="flex justify-between items-center bg-bg2/35 px-2 py-1 rounded">
                              <span className="text-text3">{formattedKey}</span>
                              <span className="font-semibold text-text">{String(val)}</span>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
