import { useEffect, useState } from 'react';
import { useAuth } from '@/lib/auth';
import { ai as aiApi } from '@/lib/api';
import GuestGate from '@/app/components/GuestGate';
import { Loader2, Sparkles, Smile, Compass, Flame, Activity, TrendingUp, Heart } from 'lucide-react';

export default function Insights() {
  const { user } = useAuth();
  
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [insightsData, setInsightsData] = useState<{
    calmness_score: number;
    consistency_index: number;
    interaction_focus: string;
    insights: string[];
  } | null>(null);
  
  const [stats, setStats] = useState<{
    total_moods: number;
    avg_mood: number;
    total_journals: number;
    total_rituals: number;
    total_clicks: number;
    total_navigations: number;
    top_page: string;
  } | null>(null);

  useEffect(() => {
    if (!user) {
      setLoading(false);
      return;
    }

    async function fetchInsights() {
      try {
        const res = await aiApi.get30DayInsights();
        if (res.success) {
          setInsightsData(res.data);
          setStats(res.stats);
        } else {
          throw new Error('Failed to generate insights.');
        }
      } catch (err: any) {
        setError(err.message || 'An error occurred while analyzing wellness report.');
      } finally {
        setLoading(false);
      }
    }

    fetchInsights();
  }, [user]);

  if (!user) {
    return (
      <GuestGate
        title="30-Day AI Wellness Report"
        description="Sign in to view your personalized behavior patterns, emotional trends, and daily guidance generated by ARIA."
        icon={<Activity className="w-8 h-8 text-accent animate-pulse" />}
      />
    );
  }

  if (loading) {
    return (
      <div className="min-h-[50vh] flex flex-col items-center justify-center space-y-4">
        <Loader2 className="w-8 h-8 text-accent animate-spin" />
        <p className="text-sm text-text3">Analyzing your 30-day activity logs & training ARIA's memory...</p>
      </div>
    );
  }

  if (error || !insightsData || !stats) {
    return (
      <div className="max-w-md mx-auto text-center space-y-4 py-12">
        <div className="text-rose text-lg">⚠️ Wellness Analysis Failed</div>
        <p className="text-sm text-text3">{error || 'Please ensure you have tracked some check-ins or rituals this month.'}</p>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-fadeIn text-left">
      {/* Title */}
      <div>
        <div className="text-xs text-accent tracking-[0.1em] uppercase mb-1">PERSONALIZED REPORT</div>
        <h1 className="text-3xl sm:text-4xl font-light text-text font-[family-name:var(--font-serif)]">30-Day AI Insights</h1>
        <p className="text-sm text-text3 font-light mt-1">Behavior patterns & custom wellness recommendations generated by ARIA.</p>
      </div>

      {/* Grid of Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        
        {/* Calmness Score Card */}
        <div className="bg-bg2 border border-border rounded-[20px] p-6 space-y-4 relative overflow-hidden shadow-lg">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,rgba(16,185,129,0.05),transparent_60%)] pointer-events-none" />
          <div className="flex items-center justify-between">
            <span className="text-xs text-text3 font-medium uppercase tracking-wider">Calmness Score</span>
            <Smile className="w-5 h-5 text-emerald-400" />
          </div>
          <div className="flex items-baseline gap-2">
            <span className="text-5xl font-extralight text-text tracking-tight">{insightsData.calmness_score}</span>
            <span className="text-sm text-text3">/ 100</span>
          </div>
          <p className="text-xs text-text2 font-light leading-relaxed">
            Measures your average emotional stability and recovery rate based on your mood logs.
          </p>
        </div>

        {/* Consistency Index Card */}
        <div className="bg-bg2 border border-border rounded-[20px] p-6 space-y-4 relative overflow-hidden shadow-lg">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,rgba(245,158,11,0.05),transparent_60%)] pointer-events-none" />
          <div className="flex items-center justify-between">
            <span className="text-xs text-text3 font-medium uppercase tracking-wider">Consistency Index</span>
            <Flame className="w-5 h-5 text-amber" />
          </div>
          <div className="flex items-baseline gap-2">
            <span className="text-5xl font-extralight text-text tracking-tight">{insightsData.consistency_index}</span>
            <span className="text-sm text-text3">/ 100</span>
          </div>
          <p className="text-xs text-text2 font-light leading-relaxed">
            Your habit score based on morning intentions set and evening wind down exercises completed.
          </p>
        </div>

        {/* Focus Feature Card */}
        <div className="bg-bg2 border border-border rounded-[20px] p-6 space-y-4 relative overflow-hidden shadow-lg">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,rgba(139,92,246,0.05),transparent_60%)] pointer-events-none" />
          <div className="flex items-center justify-between">
            <span className="text-xs text-text3 font-medium uppercase tracking-wider">Primary Habit</span>
            <Compass className="w-5 h-5 text-violet-400" />
          </div>
          <div className="flex items-baseline">
            <span className="text-2xl font-light text-text tracking-tight truncate w-full">{insightsData.interaction_focus}</span>
          </div>
          <p className="text-xs text-text2 font-light leading-relaxed pt-2">
            The core feature you interacted with the most during this 30-day tracking window.
          </p>
        </div>

      </div>

      {/* Main AI Advisory Panel */}
      <div className="bg-bg2 border border-border rounded-[24px] p-6 sm:p-8 space-y-6 relative overflow-hidden shadow-xl">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,rgba(233,75,111,0.06),transparent_60%)] pointer-events-none" />
        
        <div className="flex items-center gap-3 border-b border-border/80 pb-4">
          <div className="w-10 h-10 rounded-full bg-accent/10 flex items-center justify-center text-accent">
            <Sparkles className="w-5 h-5 animate-pulse" />
          </div>
          <div>
            <h3 className="font-semibold text-text text-base">ARIA's Memory & Guidance</h3>
            <p className="text-xs text-text3">Based on your clicks, logs, and interaction telemetry.</p>
          </div>
        </div>

        <ul className="space-y-4">
          {insightsData.insights.map((insight, idx) => (
            <li key={idx} className="flex items-start gap-4 text-sm text-text2 leading-relaxed">
              <div className="w-6 h-6 rounded-full bg-accent/10 border border-accent/20 text-accent flex items-center justify-center shrink-0 mt-0.5 font-bold text-xs">
                {idx + 1}
              </div>
              <span className="font-light">{insight}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* Telemetry Engagement Details */}
      <div className="bg-bg3 border border-border2 rounded-[20px] p-6 space-y-6 text-left">
        <h3 className="font-[family-name:var(--font-serif)] text-lg font-light text-text flex items-center gap-2">
          <TrendingUp className="w-5 h-5 text-accent" />
          Monthly Engagement Summary
        </h3>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <div className="bg-bg2/40 border border-border/60 rounded-xl p-4 text-center">
            <div className="text-[10px] text-text3 uppercase font-medium">Mood Check-ins</div>
            <div className="text-2xl font-light text-text mt-1">{stats.total_moods}</div>
          </div>
          
          <div className="bg-bg2/40 border border-border/60 rounded-xl p-4 text-center">
            <div className="text-[10px] text-text3 uppercase font-medium">Journals Written</div>
            <div className="text-2xl font-light text-text mt-1">{stats.total_journals}</div>
          </div>

          <div className="bg-bg2/40 border border-border/60 rounded-xl p-4 text-center">
            <div className="text-[10px] text-text3 uppercase font-medium">Rituals Logged</div>
            <div className="text-2xl font-light text-text mt-1">{stats.total_rituals}</div>
          </div>

          <div className="bg-bg2/40 border border-border/60 rounded-xl p-4 text-center">
            <div className="text-[10px] text-text3 uppercase font-medium">Clicks Tracked</div>
            <div className="text-2xl font-light text-text mt-1">{stats.total_clicks}</div>
          </div>
        </div>

        <div className="border-t border-border/60 pt-4 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 text-xs text-text3 font-light">
          <div>Top Visited Area: <span className="font-semibold text-text2">{stats.top_page}</span></div>
          <div className="flex items-center gap-1">
            <Heart className="w-3.5 h-3.5 text-accent fill-accent" />
            <span>Habits create routines. Keep reflecting daily!</span>
          </div>
        </div>
      </div>
    </div>
  );
}
